### ISSUE TITLE
One Hundred Blades should deal 1 damage to Salamander Monk Spirit and Shadow Hound

### ISSUE THREAD

**Issue by donovanamitchell** [Ashteki/ashteki#1010]
Played a game in which the only units on the board were 1 Salamander Monk Spirit and 1 Shadow Hound owned by a Hope opponent. I, playing as Coal, played a One Hundred Blades which should have dealt one damage to both of my opponent's units. It dealt one damage to Hope, who reacted with a Sympathy Pain to deal two damage to Coal. The rest of One Hundred Blades did not resolve.

Excerpt from the game logs
```
 Squareical attacks Hope Everthorn with Time Hopper, Time Hopper, and Time Hopper
hotraisinz uses Salamander Monk to block against Time Hopper
hotraisinz has chosen defenders
Resolving attack from Time Hopper
Hope Everthorn takes 1 damage
Resolving attack from Time Hopper
Hope Everthorn takes 1 damage
Resolving attack from Time Hopper
Salamander Monk takes 1 damage
Time Hopper takes 1 damage
hotraisinz uses Salamander Monk
hotraisinz puts Salamander Monk Spirit into play
Salamander Monk is destroyed
Time Hopper is destroyed
Turn 2 - hotraisinz
hotraisinz meditates River Skald from their hand to change from  to 
hotraisinz meditates Summon Shadow Hound from their hand to change from  to 
hotraisinz meditated 2 cards/dice
hotraisinz uses Summon Shadow Hound
hotraisinz puts Shadow Hound into play
Time Hopper is destroyed
Time Hopper is destroyed
Turn 2 - Squareical
Squareical plays One Hundred Blades to deal 1 damage to Hope Everthorn and all opponent's units
hotraisinz plays Sympathy Pain to deal 2 damage to oppponent's unit or phoenixborn
```

**Comment by danj3000** [comment]
OneHundredBlades has changed recently - it now follows the AoE ordering like natures wrath, meteor etc. 
At this point in the process you should have been presented with a prompt to then select the order in which to resolve the damage events to the targets.

I have just added a test to make sure that 100blades continues after a Sympathy pain, and it passes. But that is just a happy path test. perhaps something else is happening here. Do you remember whether the SP damage was applied to the PB or to a unit?

**Comment by donovanamitchell** [comment]
The Sympathy Pain damage was applied to Coal

**Comment by danj3000** [comment]
Fix deployed.
