### ISSUE TITLE
GT Turbo option

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#1078]
> I think I want the ability to disable to group tactics option in my options.
like if that 1 in 10,000 thing where I don't want it ever comes up in real life I'll just manual it.

**Comment by onecrayon** [comment]
Alternately:

1. If 1 GT unit: same prompt as now
2. If >1 GT unit: generic "do you want to use Group Tactics" prompt with "Yes", "No", and "Pick and choose" options (first two opt in or out for the whole group, last one lets you do one by one like the current implementation)
