### ISSUE TITLE
Opponent looking at deck not announced in chat 

### ISSUE THREAD

**Issue by Melkor118** [Ashteki/ashteki#146]
When an opponent clicks on their deck there is no announcement in the chat, the cards look to be sorted alphabetically but knowing EXACTLY what cards are left in your deck without an announcement is a bit dodge.

**Comment by danj3000** [comment]
I don't know...., in theory you know the deck list and can look at the discard pile, so it's only saving you having to go through a longer process to determine what's left.
The alpha sort prevents you knowing anything that's not open information already.

Having said that, I don't mind adding the message, as it lets your opponent know your having a good long think :-D

**Comment by Melkor118** [comment]
I agree, it's really just the fact that they can look at the actual cards left rather then just utilising their discard pile and decklist which would be how you would do it in person.

It's certainly not a huge issue since the deck is sorted and not in the actual draw order

**Comment by 5H4Z** [comment]
I don't think that this announcement is required. While you couldn't do this as easily in a physical game, this helps with effects that let you search your deck for an effect, leading to less manual mode issues. The only benefit from having a message is that it might tell you why an opponent is taking a while taking their turn.
