### ISSUE TITLE
Not sure if README needs update

### ISSUE THREAD

**Issue by OneFabric** [Ashteki/ashteki#1514]
Hi!

I am trying to see if I can follow the instructions from the README.  The command `docker-compose up` did not work for me; I got the error `no configuration file provided: not found`. I saw a note saying the README may need to be updated.

I wanted to check to see if the error is on my end before proceeding further.

I can provide more details, or just go through the codebase myself - either works. Thanks for your time!

**Comment by danj3000** [comment]
it should be fine - a couple of guys in the discord have successfully set up recently. 
There's also a #software-dev channel in the discord that has some discussion from recent attempts.
