### ISSUE TITLE
UI Request: Enlarged Card Display popup. Could this be next to the hovered card?

### ISSUE THREAD

**Issue by DM-miX** [Ashteki/ashteki#218]
Hi Dan.
I find my concentration go a little looking to the bottom right to see my cards, but then to the top left to see the enlarged card.

Feel like it would be better if the popup was right at the card near the mouse.
Perhaps as an option?

Cheers,
Mick

**Comment by danj3000** [comment]
Left layout makes this closer to the action, so closing here
