### ISSUE TITLE
Undying Heart causing issues?

### ISSUE THREAD

**Issue by newtaj** [Ashteki/ashteki#292]
My opponent attacked me for two I Redirected the damage to my Blood Shaman which had previously been returned to my hand with Undying Heart.  The Shaman lived, I think this is due to it still having the buff from Undying but I don't know.

I copied the chat log

-taj brings Jessa Na Ni to battle
Loren17 brings Koji Wolfcub to battle
 -taj has connected to the game server
 Loren17 has connected to the game server
-taj has chosen their first five
 PaulGrogan has joined the game as a spectator
-taj
good luck
Loren17 has chosen their first five
ROUND 1
Prepare phase
-taj rolls 7 basic dice
Loren17 rolls 3 basic dice
 -taj rolled the most basics so will choose first player
Loren17
enjoy
 PaulGrogan has left the game
-taj
Hey I'll hang around to finish if you have to go but I'm not sure if you just get caught up or not?
 -taj chooses to go second
Loren17
ya i was trying to type an apology when the game began
-taj
Yeah it's not a big deal at all for sure
Loren17
i wa called away sudenl;y and didn't get back for quute a while but i will try to let youknowbetter this time if i have to go
Loren17 has not discarded
Loren17
ouch 7 basics!
-taj
It's fine to have other priorites.
-taj has not discarded
Playerturns phase
Turn 1 - Loren17
Loren17 plays Guilt Link
Loren17 meditates Redirect to gain a 
-taj
I'm usually pretty okay with meditating my cards as long as I'm not facing a mill deck
Loren17 meditates Seeds Of Aggression to gain a 
Loren17 meditated 2 cards/dice
Turn 1 - -taj
-taj plays Summon Blood Puppet
Turn 2 - Loren17
Loren17 plays Summon Indiglow Creeper
Turn 2 - -taj
-taj plays Blood Transfer
Turn 3 - Loren17
Loren17 plays Open Memories to place a card into their hand
Turn 3 - -taj
Loren17
7 is a lot on the first turnpotentially though
Loren17
my deck only uses one basic in the first round and it has tobe a nature
-taj meditates Summon Blood Puppet to gain a 
-taj meditates Living Doll to gain a 
-taj meditated 2 cards/dice
-taj plays Blood Archer
Turn 4 - Loren17
Loren17 plays Summon Indiglow Creeper
Turn 4 - -taj
-taj
My PB ability is going to be important here
Loren17
true butitalways feels har dto spend those dice round one
-taj plays Living Doll
Turn 5 - Loren17
Loren17 plays String Mage
Loren17 uses Koji Wolfcub to place 1 status on Guilt Link
Turn 5 - -taj
-taj uses Summon Blood Puppet to put Blood Puppet into play
Turn 6 - Loren17
Loren17 uses Summon Indiglow Creeper to put Indiglow Creeper into play
Turn 6 - -taj
-taj uses Blood Archer to deal 1 damage to a unit
Loren17 uses Indiglow Creeper to put Luminous Seedling into play
Indiglow Creeper is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Koji Wolfcub
 -taj attacks Koji Wolfcub with Blood Puppet
Loren17 has chosen defenders
Turn 7 - Loren17
Loren17 uses Summon Indiglow Creeper to put Indiglow Creeper into play
Loren17 uses String Mage to move 1 status token from String Mage to Luminous Seedling
Turn 7 - -taj
-taj plays Fear to destroy Blood Puppet
Blood Puppet is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Koji Wolfcub
-taj uses Blood Archer to deal 1 damage to a unit
Loren17 uses Indiglow Creeper to put Luminous Seedling into play
Indiglow Creeper is destroyed
Turn 8 - Loren17
Loren17 plays Invigorate to place 1 status on Luminous Seedling and String Mage
 Loren17 PASSES their main action
Turn 8 - -taj
 -taj PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
-taj keeps 0 dice
Loren17 keeps 0 dice
End of round 1
ROUND 2
Prepare phase
Loren17 has not discarded
-taj has not discarded
Playerturns phase
Turn 1 - -taj
Loren17
i will be about2 minutes
-taj
thx
-taj plays Fear to destroy Living Doll
Living Doll is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Koji Wolfcub
-taj plays Final Cry to deal 2 damage to oppponents phoenixborn
-taj uses Blood Archer to deal 1 damage to a unit
Turn 1 - Loren17
Loren17
back
Loren17 uses Summon Indiglow Creeper to put Indiglow Creeper into play
Loren17 uses String Mage to move 1 damage token from String Mage to Blood Archer
Turn 2 - -taj
-taj uses Summon Blood Puppet to put Blood Puppet into play
Turn 2 - Loren17
Loren17 uses Summon Indiglow Creeper to put Indiglow Creeper into play
Turn 3 - -taj
-taj meditates Living Doll to gain a 
-taj meditated 1 cards/dice
 raopper has joined the game as a spectator
-taj plays Blood Shaman
Turn 3 - Loren17
 Loren17 attacks Blood Shaman with Indiglow Creeper
-taj uses Jessa Na Ni to guard
Jessa Na Ni takes 2 damage
Loren17 meditates Seeds Of Aggression to gain a 
Loren17 meditates Redirect to gain a 
Loren17 meditated 2 cards/dice
Turn 4 - -taj
-taj plays Blood Archer
-taj uses Blood Archer to deal 1 damage to a unit
Blood Archer is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Koji Wolfcub
Loren17 uses Indiglow Creeper to put Luminous Seedling into play
Indiglow Creeper is destroyed
Turn 4 - Loren17
Loren17 plays Nature's Wrath to deal 1 damage to all units
Indiglow Creeper is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Koji Wolfcub
Loren17 uses String Mage to move 1 damage token from String Mage to Blood Archer
Turn 5 - -taj
-taj uses Blood Archer to deal 1 damage to a unit
Blood Archer is destroyed
Luminous Seedling is destroyed
 -taj PASSES their main action
Turn 5 - Loren17
Loren17 plays Raptor Herder
Loren17 uses Raptor Herder to put Raptor Hatchling into play
-taj
As long as I'm not getting a face full of thorn
Loren17 meditates Invigorate to gain a 
Loren17 meditated 1 cards/dice
Turn 6 - -taj
 -taj PASSES their main action
Turn 6 - Loren17
Loren17 plays String Mage
Turn 7 - -taj
 -taj PASSES their main action
Turn 7 - Loren17
 Loren17 attacks Blood Puppet with Raptor Herder
Blood Puppet takes 1 damage
Blood Puppet is destroyed
Loren17 uses Koji Wolfcub to place 1 status on String Mage
Turn 8 - -taj
 -taj PASSES their main action
Turn 8 - Loren17
Loren17 uses Raptor Hatchling to increase its attack value by 2
 Loren17 attacks Jessa Na Ni with String Mage, Raptor Hatchling, and String Mage
-taj uses Blood Shaman to block against Raptor Hatchling
Jessa Na Ni takes 1 damage
Blood Shaman takes 2 damage
Blood Shaman is destroyed
Jessa Na Ni takes 1 damage
Loren17 plays Lick Wounds to remove 2 damages from Koji Wolfcub
Turn 9 - -taj
 -taj PASSES their main action
Turn 9 - Loren17
Loren17 uses Koji Wolfcub to place 1 status on String Mage
 Loren17 PASSES their main action
 Both players passed their main action.
Recovery phase
All units recover wounds where able.
All cards remove one exhaustion token.
Loren17 keeps 0 dice
-taj keeps 0 dice
End of round 2
ROUND 3
Prepare phase
-taj has not discarded
Loren17 has not discarded
Playerturns phase
Turn 1 - Loren17
Loren17 uses Raptor Hatchling to increase its attack value by 2
 Loren17 attacks Jessa Na Ni with String Mage, Raptor Hatchling, and Raptor Herder
Jessa Na Ni takes 1 damage
Jessa Na Ni takes 2 damage
Jessa Na Ni takes 1 damage
Loren17 meditates Call Upon The Realms to gain a 
Loren17 meditates Summon Indiglow Creeper to gain a 
Loren17 meditated 2 cards/dice
Turn 1 - -taj
-taj plays Blood Shaman
-taj plays Undying Heart attaching it to Blood Shaman
Turn 2 - Loren17
Loren17 uses Summon Indiglow Creeper to put Indiglow Creeper into play
Loren17 uses Guilt Link to destroy Raptor Herder
Raptor Herder is destroyed
-taj chooses to destroy Blood Shaman
-taj uses Blood Shaman to return Blood Shaman to hand
Blood Shaman is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Koji Wolfcub
Turn 2 - -taj
-taj plays Blood Shaman
Turn 3 - Loren17
 Loren17 attacks Blood Shaman with Indiglow Creeper
-taj uses Jessa Na Ni to guard
-taj plays Redirect to redirect the damage
Blood Shaman takes 2 damage
Loren17
shouldn't it be dead?
-taj
it's waiting on you to react
-taj
is'nt it?
Loren17
my screen in not reacting
-taj
okay, uh?
 Loren17 is attempting to switch manual mode on
 -taj allows enabling manual mode
 Loren17 switches manual mode on
 -taj manually moves Blood Shaman from their play area to their discard
 Loren17 switches manual mode off
 -taj is attempting to switch manual mode on
 Loren17 allows enabling manual mode
 -taj switches manual mode on
-taj
I get a heal
Loren17
ok
 -taj removes a damage from Jessa Na Ni
 -taj switches manual mode off
Loren17
and the dice fixing
 -taj is attempting to switch manual mode on
 Loren17 allows enabling manual mode
 -taj switches manual mode on
-taj
ah yeah I could use that
 -taj raises ceremonial basic die
Turn 3 - -taj
 -taj lowers ceremonial class die
 -taj raises ceremonial basic die
 -taj switches manual mode off
-taj meditates Undying Heart to gain a 
-taj meditated 1 cards/dice
-taj uses Summon Blood Puppet to put Blood Puppet into play
Turn 4 - Loren17
Loren17 plays Summon Squall Stallion
Turn 4 - -taj
-taj
I need that darn Living Doll
Loren17
you can grab with your dice...
-taj
yeah, brb
Loren17
np
 raopper has left the game
-taj
Thanks
-taj plays Fear to destroy Blood Puppet
Blood Puppet is destroyed
-taj uses Jessa Na Ni to deal 1 damage to Koji Wolfcub
-taj uses  to move Living Doll from discard to hand, and receives 1 PB damage
Turn 5 - Loren17
-taj
I needed her a couple rounds ago
-taj
Might be able to get me this round but you might have too many sides
Loren17
here
Loren17 uses Summon Squall Stallion to draw 1 cards
Loren17 uses Squall Stallion to return String Mage to the bottom of their deck
Loren17 returns a card to the bottom of their deck
Turn 5 - -taj
-taj meditates Redirect to gain a 
-taj meditated 1 cards/dice
 -taj PASSES their main action
Turn 6 - Loren17
Loren17 uses Summon Indiglow Creeper to put Indiglow Creeper into play
 Greystorm has joined the game as a spectator
Loren17
be back
 Greystorm has joined the game as a spectator
-taj
hi

**Comment by danj3000** [comment]
I think you may be right. Issue #258 is a similar story.

**Comment by danj3000** [comment]
I'm closing this in the hope that it isn't an issue 6 months on 😄
