### ISSUE TITLE
Improve visual representation of stack of effects

### ISSUE THREAD

**Issue by TheHorribleDrB** [Ashteki/ashteki#299]
the situation was as follows: a mist typhoon was played by opponent. this was clear in the log window. my 2 guilders were killed. both triggered their inheritance. However there is no information (visual or otherwise) that tells me that I have 2 triggers stacked, and which one is triggered first, and which second etc... Its not a huge bug because the interface let me trigger both, this is more of a request to improve the ui to better tell the user what is happening and tell about that stack of triggering effects that have accumulated.

**Comment by danj3000** [comment]
This is a great suggestion. I'll experiment with how this could be displayed... Probably in the prompt area, but space there is a bit constrained
