### ISSUE TITLE
Improve the communication of the reason behind a request from the user.

### ISSUE THREAD

**Issue by TheHorribleDrB** [Ashteki/ashteki#300]
This is the situation: I have a summon indiglow creeper book in play and it is focused. When I summon an indiglow creeper, the focus trigger; the interface simply ask me to "pick a card"; this is confusing, I know the indiglow creeper is triggering because of the image of the card, but I dont really know that its the focus power that is being triggered. So I know what to do (pick a card), but I dont know intuitively why and what will happen to the card I chose.... This problem is a bit related to another issue I have created about improving visual representation of stack of triggering effects. so its related in the sense that I think what is going on in the game, what cards, what effects, what action etc could be better represented.

**Comment by danj3000** [comment]
Each action prompt can be tailored, e.g. 'choose a unit to destroy' when coding the card,  but in the later expansions this typically didn't get done.

I agree there is a more general point too. e.g. Where each ability has a name it should display in the prompt. Currently it only does if it has been deliberately coded that way.

**Comment by 5H4Z** [comment]
I've added some prompts that go some way towards improving this. I think in general the message prompt should be something along the lines of _Keyword: Choose a phoenixborn to damage_ and try to use the wording of the cards as much as possible without the message becoming too long. As I've been doing this, it has become clear that some changes are better to apply to the Game Actions themselves (as this allows re-use), while others should apply to the cards themselves (where you need more nuance between different prompts).

**Comment by danj3000** [comment]
A lot of messages have been improved since this was logged, so I'm going to close this. We'll continue to address specific prompts and unhelpful areas as they arise.
