### ISSUE TITLE
Notes for each deck

### ISSUE THREAD

**Issue by TheHorribleDrB** [Ashteki/ashteki#301]
This is not a bug but a feature request:
I would like to be able to take and associate some personal notes to each of my decks. Nothing fancy, something like a field that can hold 1000 characters max. It would be available to edit when editing a deck, and would be available to read during a game.
Personally I would use it to remind myself of the important concepts of my deck and what are my first 5 cards.

**Comment by 5H4Z** [comment]
I tend to uses ashes.live for that purpose - you can put your decklist in another tab and switch to it, or have it open in another browser
