### ISSUE TITLE
List of Cards Not Yet Coded

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#334]
**The following cards are not coded:**
Orrick Expansion -> now done

**These cards are not fully coded**
Echo Greystorm - tracking and removal of Gravity Flux exhaustion token must be done manually

Feedback on all other cards, e.g. messaging or bugs is welcome.

**Comment by bdwain** [comment]
orrick implementation: 
pb ability: done
ruby cobra/summon: done
captivate: done
ash spirit/summon ash spirit: #617 
fate reflection: shannon working on it
concentration/awakened state: @danj3000 working on it
flock shepherd: Not started
sunshield sentry: not started
recollect: not started
rile the meek: bryan working on it
generosity: not started

**Comment by 5H4Z** [comment]
I finally worked out fate reflection - PR #622

**Comment by 5H4Z** [comment]
All cards released to date are coded.
