### ISSUE TITLE
Summon Masked Wolf - Counldn't choose to spend Power die to use Focus 1 ability

### ISSUE THREAD

**Issue by KiwiAndSoap** [Ashteki/ashteki#425]
In a game today (4/30), I couldn't switch from spending a class die to spend a power die to utilize the focus 1 ability on Summon Masked Wolf when I had a total of two of the spells on board.  It's odd because it worked earlier in the game.  I meditated the dice up, if that matters.

**Comment by danj3000** [comment]
also reported by phillycheaz

**Comment by KiwiAndSoap** [comment]
I played with Summon Masked Wolf again and think I figured this out.  When you select the book, Ashteki automatically selects a class die.  In order to pay with a power die, you first have to unselect the class die by clicking it.  I think it is the unselecting that is causing confusion.  I haven't confirmed, but it feels like when selecting die in other instances you don't normally have to unselect a die first, it just switches when selecting a new die.
