### ISSUE TITLE
Summon spectral assassin card draw should be independent

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#439]
it's currently dependent upon the ally targetting for the summon action due to JSON structure and execution (no multiple top level then abilities

**Comment by danj3000** [comment]
Maybe handle this in 2 abilities? 'summon' and 'draw without summon' for the edge case.

**Comment by danj3000** [comment]
Just had another go at fixing this - it's a right pain. There's something in this combination of abilities that just won't play together.

Also if you have multiple this.play abilities the player gets asked which ability to resolve first :-/

**Comment by 5H4Z** [comment]
It sounds like this needs the select actions treatment similar to Small Sacrifice.

**Comment by 5H4Z** [comment]
I had a go at this. Yes, it is diabolical.
