### ISSUE TITLE
entering manual mode when attackers have been declared causes an error

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#475]
How could you amend the attackers manually?

**Comment by danj3000** [comment]
Hopefully this is not a common occurrence, as now we have more ability to step back attackers and blockers, but probably does still need checking why it errors

**Comment by 5H4Z** [comment]
I haven't seen errors in this situation. It does become more difficult to select blockers as selecting a card results in you having to then select the menu item "Select Card".

**Comment by danj3000** [comment]
old enough to close. no error directly upon entering manual when tested.
