### ISSUE TITLE
chained creations exhausts cards it should not

### ISSUE THREAD

**Issue by bdwain** [Ashteki/ashteki#538]
if you use chained creations on a salamander monk spirit, it lets you exhaust summon salamander monk. it should not let you do that, as the ready spell does not place a spirit on the board. 

I didn't test this with other units like that (such as luminous seedlings and brilliant thorns), but they also should be fixed if they exhibit the same bug.

**Comment by 5H4Z** [comment]
Confirmed that this bug affects both Summon Salamander Monk and Summon Indiglow Creepers
