### ISSUE TITLE
Update echo token removal to work on trust basis

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#596]
Enforcement is not possible without tokens being game objects

**Comment by bdwain** [comment]
could you set up a persistent effect until end of round to unexhaust the card that got gravity fluxed. and also one that says if we move an exhaustion from that card to another card, remove the listener, and add it to the card that just got transferred?

**Comment by danj3000** [comment]
Maybe... Could get complicated if the card has 2 tokens. You'd need prompts at each step to ask if you're moving the echo token.

Other option would be to create a token object that attaches like a die, and messes with the exhaustion count.
