### ISSUE TITLE
game should shut down when I leave if opponent has disconnected

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#607]
I think this is an issue that needs fixing - if player1 disconnects from the game, and then player2 clicks leave, the game sticks around and player1 can reconnect, and in fact keep playing their turn. which makes not sense. I think as soon as player 2 leaves the game if player 1 is not connected then the game should be shut down.

**Comment by 5H4Z** [comment]
That is strange and I could confirm that it occurs in production and in testing. Player1's reconnect occurs as soon as they select the Play tab. Once player1 selects Leave, the game node shuts down as it should have originally.

I noticed a similar issue that only appears locally during testing (I have not been able to reproduce it in production). If player1 leaves directly (without any player specifically selecting concede first), and then player2 leaves, the game stays up without anyone being able to join it, appearing like player1 is still in the game. The node persists for around 5 minutes. Player1 cannot rejoin the game in that instance. The workaround is to make sure that a player has specifically selected Concede prior to players leaving the game.
