### ISSUE TITLE
 transfer does not target cards

### ISSUE THREAD

**Issue by bdwain** [Ashteki/ashteki#613]
transfer does not target a card (it targets a player), so it has a few bugs associated with it

1. you SHOULD NOT be able to play golden veil to cancel it
2. you SHOULD be able to play vanish to cancel it
3. you SHOULD be able to use it units with magic armor (e.g. holy knight)
4. you SHOULD be able to use it on concealed units (shadow hound and stormwind sniper)

Note: It looks like holy knight is currently implemented using the same ability (spell guard) as cards like summon silver snake and massive growth. but those abilities are actually different (and not just because holy knight's ability is exhaustible). Holy knight's magic armor prevents targeting, while spell guard prevents ALL effects (including non-targeting effects). so transfer could not be used on massive growth or summon silver snake for example (which it currently does not allow). My guess is that we'll need to separate holy guard from the spell guard ability, which seems to function properly as-is, just not on holy knight, which should not have it anyway

**Comment by danj3000** [comment]
vanish interaction moved to #718
