### ISSUE TITLE
safeguard and sacred ground do not work across rounds

### ISSUE THREAD

**Issue by bdwain** [Ashteki/ashteki#666]
if  do sacred ground + pass (or side action plus pass) and then you pass (or my turn was the last turn of the round) and you start the following round, those cards should still be in effect for your first turn the following round. They don't currently do that.

THis is also true for lightbringer. I'm unsure if it is broken though

**Comment by 5H4Z** [comment]
My testing so far: Sacred Ground lasts when I side action Sacred Ground + pass ending the round, and then I start the new round (it shouldn't - the effect should end at the start of my new turn). When I then finish that turn, the effect ends.
Sacred Ground doesn't last when I side action Sacred Ground + pass, then the opponent ends the round and then my opponent starts the new round (it should - the effect is supposed to end at the start of my new turn).

**Comment by bdwain** [comment]
i wrote some unit tests for these bugs. i'll open a pr with them. have not done the fixes yet

**Comment by bdwain** [comment]
https://github.com/danj3000/ashteki/pull/670/files

**Comment by bdwain** [comment]
i think we can fix it by using something like

```
until: {
   onBeginTurn: (event) => event.player === properties.context.player
},
```

which is used in captivate. but i want to make a standarddized thing for it. `untilNextTurn` seems to be a standardized idea across the app but it's wrong. it is based on number of turns, which is not correct around end of round boundaries. so i want to delete that as a concept and replace it with `untilMyNextTurn` which is based on the `until` thing above. or `throughOpponentTurn` for something like lightbringer (which is a bit different than safeguard or sacred ground).

also, the safeguard bug is a bit weird with tests because safeguard has a second bug right now where it protects against your own effects, which it should not do. #667
