### ISSUE TITLE
SENTRY: meditate error

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#692]
can't read location property of cards[0]
https://sentry.io/share/issue/2a90eda8db1a4570845584a09cc03964/

**Comment by 5H4Z** [comment]
Ah, this is likely a bug with my implementation of the messages to say where the card meditated came from.

**Comment by danj3000** [comment]
Yes, but cards[0] should not be null, so a bit of an odd one. 
(This is only making the jump into an issue because sentry errors have really dropped to a small number 😄)

**Comment by 5H4Z** [comment]
I don't really understand how sentry works, but I am guessing that this could be related to issue #690. If cards[0] was filled during the resolution of a reaction spell, rather than being explicitly selected by a player, perhaps the location was undefined at that point in time?
