### ISSUE TITLE
Body Inverted Silver Snake Didn't Die

### ISSUE THREAD

**Issue by 5H4Z** [Ashteki/ashteki#697]
This may be related to the "X is not 0" fix?
![image](https://user-images.githubusercontent.com/89332227/134759845-96a88f39-63d8-453e-9da4-e78238fe088b.png)

**Comment by 5H4Z** [comment]
@bdwain This may be of interest to you as it appears related to your recent fix

**Comment by bdwain** [comment]
Interesting. I could definitely see that being related. I’m away from a computer for a few days though so I won’t be able to look right away
