### ISSUE TITLE
Mind fog owl focus didn't trigger

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#722]
Inquisitor
I think we ran into an issue in a game I just played. I had focused mind fog owl books up and paid to activated it with charm power but I did not get to subsequently resolve the charm die power

**Comment by 5H4Z** [comment]
We probably need some additional information to track this down as the logic seems pretty simple and it was working for me during testing just now. The prompt for Mind Fog Owl focus is pretty poor, so perhaps that led to the power die placement being clicked through.
