### ISSUE TITLE
charmed sunshield sentry was able to block a frostback bear

### ISSUE THREAD

**Issue by bdwain** [Ashteki/ashteki#727]
https://discord.com/channels/356912698451296276/752956497947787404/894039922309230664

~I was not able to reproduce~

EDIT: I was. They attackd with frostback bear and mindfog owl

<img width="303" alt="Screen Shot 2021-10-02 at 10 13 01 PM" src="https://user-images.githubusercontent.com/3982094/135738151-c017525b-f567-4edc-9f98-7fd7a0c395e8.png">

the Mindfog owl's ability somehow allows the sentry to block accidentally (though neither are highlighted as blockable)

**Comment by 5H4Z** [comment]
I wrote a test for the case where there was a charmed Iron Worker in this situation, and it couldn't block the bear or the owl in this circumstance. I'll investigate whether there is something odd about the Sunshield Sentry by writing a similar test.

**Comment by 5H4Z** [comment]
Sunshield Sentry was similarly unable to block in the test. Was there anything else that you had to setup, @bdwain , to re-create this?

**Comment by 5H4Z** [comment]
Ah, I've worked it out. The "to be able to select" is false, but you can still go ahead and select the blocker and the Bear and get them into battle in both instances. So it doesn't matter which unit has reduced attack. There is an odd interaction between Terrifying and Unseen that is going on.

**Comment by 5H4Z** [comment]
The full description of the bug appears to be: "if you attack with a unit with terrifying and a unit with unseen, even though attacker highlighting appears correctly, any unit can block the terrifying unit and/or the unseen unit". In my test, an Anchornaut can block the Bear, and then it can change selection to instead block the Mindfog Owl.

**Comment by 5H4Z** [comment]
Unseen only checks that all the other units have been blocked, which means after you have blocked the other units, you can then change one of those blocking units to instead block the Unseen unit (which should not be legal).
![image](https://user-images.githubusercontent.com/89332227/135782594-e1259c70-808c-4fb0-a20c-d49a9d2c5da1.png)

**Comment by 5H4Z** [comment]
Terrifying isn't preventing blocking though it is correctly greying out which units you should not be able to block: 
![image](https://user-images.githubusercontent.com/89332227/135783107-a5f7ed97-1b84-48df-af72-e08fd57a639d.png)
