### ISSUE TITLE
Copycat is not working correctly with Phoenix Barrage

### ISSUE THREAD

**Issue by 5H4Z** [Ashteki/ashteki#745]
**Carl:** Fate Reflection seems to cancel the remainder of the effects like Golden Veil does.

**waves**: The Fate Reflection one was weird. I copycatted a Phoenix Barrage. I think what happened was the first instance of the copycatted Phoenix Barrage wasn't there (the prompt said "choose another unit to target" for the first target I believe). This "second" instance was fate reflected, and the third seemed to go off like normal. So it might just be related to Copycat and Phoenix Barrage, but I'm not sure.

**Comment by danj3000** [comment]
Most likely a copycat thing see #630

**Comment by 5H4Z** [comment]
Agreed. The majority of the Fate Reflection code is exactly the same as Angelic Rescue, so I don't think that would be the issue.

**Comment by 5H4Z** [comment]
Testing of Copycat with Phoenix Barrage found that Phoenix Barrage only provided a trigger at the end of the 3 effects (as expected), but if there were no longer any units in play, Copycat did not skip over the unit targetting and then allow PB damage. e.g.
test1 plays Phoenix Barrage to deal 2 damage to Shadow Spirit
Shadow Spirit is destroyed
Shadow Hound is destroyed
test2 plays Copycat to resolve Copycat's ability

The follow up test where there were 2 legal unit targets found that Copycat started at the "Select a Second Unit Target" effect and did indeed allow targetting the PB after that one lot of 2 damage.

**Comment by 5H4Z** [comment]
The event messages for Phoenix Barrage are patchy - it only shows the first 2 damage, and unit destruction instead of mentioning each effect including the PB damage. e.g.
test1 plays Phoenix Barrage to deal 2 damage to Shadow Spirit
Shadow Spirit is destroyed
Shadow Spirit is destroyed
test2 plays Copycat to resolve Copycat's ability
Emberoot Lizard is destroyed
