### ISSUE TITLE
Shelter Canyon units should remove their other tokens

### ISSUE THREAD

**Issue by 5H4Z** [Ashteki/ashteki#746]
carl: Shelter Canyon's unit came into play with wound and exhaustion tokens it had prior to being placed under Shelter Canyon.

**Comment by danj3000** [comment]
Rtol:
@dijon this happened to me when Fiona used it twice a round by unexhausting it with her ability or Gates

**Comment by 5H4Z** [comment]
Waves: seaside raven comes into play exhausted and doesn't get prey 2 after being returned from the canyon shelter
