### ISSUE TITLE
unclear issues with royal charm, finch, and awakened state

### ISSUE THREAD

**Issue by bdwain** [Ashteki/ashteki#757]
https://discord.com/channels/356912698451296276/752956497947787404/897612291988680705

Nick Conley (he/him) — Today at 5:30 PM
Perhaps related to royal charm, I've seen a blocking finch inexplicably deal 1 counter dmg vs my attacking Cobra

Nick Conley (he/him) — Today at 5:33 PM
and 0 atk units pingable by Awakened State when Flock Shep is up

**Comment by 5H4Z** [comment]
Orchid Dove also deals one damage when countering the Cobra unit attack. Nightshade Swallow attacked does not deal increased damage when it counters.
