### ISSUE TITLE
Manual mode clean ups

### ISSUE THREAD

**Issue by 5H4Z** [Ashteki/ashteki#761]
The /passactive chat command doesn't seem to end the turn correctly as Ruby Cobra kept its attack bonus during the next turn.
Some menus repeatedly show up in each Manual Mode, for instance when I select an opponent's die. There should be a way of clearing those menus each time that Manual Mode ends.

**Comment by 5H4Z** [comment]
I confirmed that /passactive results in "for the remainder of turn effects" like Flash Strike continuing indefinitely.

**Comment by danj3000** [comment]
closing - have raised new issue for menu stuff
