### ISSUE TITLE
Return Alteration from Discard on Polarity Mage Option

### ISSUE THREAD

**Issue by kphelps-hub** [Ashteki/ashteki#861]
Confirmed by our rules Lord, Skaak. You should still get the option to return an alteration to hand even if you have no alterations in the discard. Also, the options are not easy to read with the buttons and I think should be shortened.

From discord:
question on Pmage if you have no alterations in the discard, but a root armor in play on your own unit, do you have to discard it? 

[polarity mage]
Ashes.bot
BOT
 — Today at 4:37 PM
Polarity mage

Kaile Phelps — Today at 4:38 PM
it says you "may... do x, or y" - does that language mean that you have to do one or the other if you can?
Skaak — Today at 4:38 PM
"you may" applies to the whole thing; you can opt to do nothing
Kaile Phelps — Today at 4:39 PM
ok - I assume that's the intent, but the wording is kind of weird
Skaak — Today at 4:39 PM
Even if it was otherwise, you could just choose to return an alteration from your discard, even if there wasn't one there (and "do as much as possible" which in this case would be nothing)

**Comment by 5H4Z** [comment]
Both actions are optional, so you can always select Done and not carry out the selected option. I think having an option to return an alteration from your discard pile when none is there to target will lead to more confusion than the current pruning of options if none is available. 

Do you have any suggested wording that fits with the intent of the card? The buttons are currently Return to hand and Discard from play. Would Return alteration / Discard alteration be easier to read?

**Comment by 5H4Z** [comment]
Hm, Return alteration / Discard alteration is actually longer. Perhaps "Return card / Discard card" ?

**Comment by kphelps-hub** [comment]
I think what would help the most with clarity for the polarity mage is to have 3 buttons: Return to Hand/Discard from play/Done. The prompt is confusing if you have a root armor in play and nothing in the discard pile and it seems like ashteki is going to force you to discard the root armor. 

As for the wording, honestly, I like the wording as it is. Are the buttons able to be extended or cover multiple rows?
