### ISSUE TITLE
Purge

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#863]
Rtol: I'm not sure if you can Purge yourself in Ashteki like you should, since it says player, it almost came up in my game :D

**Comment by 5H4Z** [comment]
Glow Finch, Summon Nightshade Swallow, Orchid Dove too. Return to Soil should mill and remove cards from the discard pile from the controller of the unit.

**Comment by 5H4Z** [comment]
I'm not sure that there is any use case though, for the first four. You can always Purge your opponent even when they have no cards in deck if you are looking to use up main actions.

**Comment by 5H4Z** [comment]
The PR fixed Purge. I don't think it is worth adding similar code to the Finch, Summon Swallow or Orchid Dove. I've made a new ticket for Return to Soil.
