### ISSUE TITLE
Meditate from an unknown location

### ISSUE THREAD

**Issue by 5H4Z** [Ashteki/ashteki#884]
Inquisitor was meditating and it wasn't responding to his dice clicks. When he refreshed, the message log had a "meditates from an unknown location" for each of the clicks that he made while it wasn't responding, and it didn't look like he'd actually disconnected.

**Comment by 5H4Z** [comment]
The steps were that Inquisitor clicked confirm, then didn't receive any prompt about which card was meditated from the top of deck, so then he tried clicking confirm a few more times, Clear Selection. When he went back to the lobby and in again, it seemed to work. I'm not sure whether having another tab with ashteki open may have been a contributing factor. ![image](https://user-images.githubusercontent.com/89332227/153728113-33f7c27b-5707-4c98-b543-a3fbe4b0edde.png)

**Comment by 5H4Z** [comment]
![image](https://user-images.githubusercontent.com/89332227/153728209-de4ef893-07b8-4f2a-8e42-0c71b6bed9ee.png)

**Comment by danj3000** [comment]
Having more than one window open and logged in with the same user definitely makes the site unhappy on a socket.io level

**Comment by 5H4Z** [comment]
I think we can close this for now and see if it is spotted when this situation of dual ashteki windows is not observed.
