### ISSUE TITLE
Check exhaustion tokens are in manual mode

### ISSUE THREAD

**Issue by 5H4Z** [Ashteki/ashteki#885]
Inquisitor was in manual mode, however he didn't have the option to add or remove an exhaustion token from his Vampire Bat Swarm. The option to add a Gravity Flux token was there.

**Comment by 5H4Z** [comment]
Possibly a resolution issue? ![image](https://user-images.githubusercontent.com/89332227/153728307-40ce45c2-c9dc-4056-a5bc-93a12c6daa67.png)

**Comment by danj3000** [comment]
yep. tested ok.
image looks like small cards, but browser zoomed in. Exhaustion options are just above damage ones, so looks like a clipping issue.
