### ISSUE TITLE
Hope Everthorn

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#899]
~~Duplicate token~~
Keepsake
Reimagine
~~Ensnare~~
~~Double Down~~

**Comment by 5H4Z** [comment]
Double Down is coded and tested

**Comment by 5H4Z** [comment]
I have performed some additional testing with Double Down and found that OnDestroyed -> Summon allows the conjuration card that was destroyed to re-enter play (e.g. Glow Finch, Butterfly Monk). I assume that this is also the case with Summon Sleeping Widows, it just wouldn't happen in game with a conjuration count of 6.

**Comment by danj3000** [comment]
Additional testing as in this is the desired behaviour?

**Comment by 5H4Z** [comment]
Duplicate token PR #901

**Comment by 5H4Z** [comment]
Regarding Double Down, reading the rules, I think the unit should be removed from play, but it shouldn't be in the conjuration pile yet. I'll raise a question with rules on the Discord

**Comment by 5H4Z** [comment]
Confirmed that Double Down and Summon Sleeping Widows should not be able to bring the destroyed unit back into play. I'll have a look at the game state and Summon action

**Comment by 5H4Z** [comment]
Never mind, I can't count. Fixed test incoming :)

**Comment by 5H4Z** [comment]
PR #904 for Ensnare submitted
