### ISSUE TITLE
Reimagine multiples

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#917]
I notice that multiple reimagines all trigger, and if you say yes to the first the later ones ALSO still prompt you, and I suspect would 'steal' the dice already placed on the first or something like that. I think that works correctly, but results in a bunch of prompts which can be confusing. Might be niche enough to ignore tho.

**Comment by danj3000** [comment]
This isn't as easy to fix as you might think. it's bound to the fact that events trigger reactions simultaneously, and I haven't yet found the point in between prompts (if there is one) where the game can check if the dice is no longer in a state to be able to be attached.

**Comment by 5H4Z** [comment]
I'm interested in what happens if someone used Double Down with 2 power dice, one Illusion, one Time

**Comment by 5H4Z** [comment]
Ah got it, that would only be a problem if it was reaction first, then dice powers like Royal Charm

**Comment by 5H4Z** [comment]
Yep, the player is asked to order the reactions and if they say yes to each one, end up with both Reimagines being exhausted and the die moving between each one

**Comment by 5H4Z** [comment]
Would a potential solution be to add a filter for the forcedReaction to select a unique unexhausted Reimagine, since there will only ever be one power die spent at a time?
