### ISSUE TITLE
Card to meditate shown in draw pile

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#935]
> there's a (serious?) flaw wherein it shows you in the draw window which card is going to be meditated when you select top of deck; outlined in green

**Comment by 5H4Z** [comment]
game-card.selected is visible in the draw window: 
.game-card.selected {
  box-shadow: 0 0 1px 4px #009648;
}

**Comment by 5H4Z** [comment]
This is set in card.scss:
    &.selected {
        box-shadow: 0 0 1px 4px theme-color('secondary');

        &.controlled {
            box-shadow: $controlledBox, 0 0 1px 4px theme-color('secondary');
        }
    }
