### ISSUE TITLE
Feature: Elo tracking system

### ISSUE THREAD

**Issue by thetreatment** [Ashteki/ashteki#944]
Track user's casual and competitive Elo ratings within Ashteki.

Phase 1a: 
-Implement tracking option per game in game setup
-Calculate expected score and update rating for each player upon game end

Phase 1b:
-Script an updater to retroactively calculate all player's scores based on stored games

Phase 2:
-Leaderboard page to display all users scores

Phase 3?:
-Add filtering option to game lobby

For details on Elo calculation, refer to https://en.wikipedia.org/wiki/Elo_rating_system

**Comment by danj3000** [comment]
Closing. Will open another for leaderboard
