### ISSUE TITLE
Bug: Particle Shield is not triggering on Natural dice power

### ISSUE THREAD

**Issue by onecrayon** [Ashteki/ashteki#946]
Situation:

I have Particle Shield in hand, a single illusion dice on its power side in my active pool, and I have not used any reaction spells on this turn. My opponent uses the Natural dice power to hit my Sonic Swordsman for 1. If I have the bluff timer enabled, then the bluff timer triggers (but I am never prompted to play Particle Shield). If I don't have the bluff timer enabled, then my unit just takes the one damage without being prompted to play Particle Shield.

I tried backing things out with manual mode and then refreshing the browser to try the interaction again (with and without the bluff timer), and Particle Shield is just never triggering. Is it explicitly looking for a die on its class side, perhaps?

**Comment by 5H4Z** [comment]
I added a test for this situation and it acted the way that I expected. I'll see if I can replicate this in game.

**Comment by 5H4Z** [comment]
![image](https://user-images.githubusercontent.com/89332227/160227127-807633bc-f9e9-4c01-ab5d-3c7072ebda7b.png)

**Comment by 5H4Z** [comment]
I think there must be some other interaction that is part of the bug. I don't think you can reset the reaction counter via manual mode. It requires the turn to end before reactions recover for both players.

**Comment by 5H4Z** [comment]
The bluff prompt should only show up if a player hasn't already used their reaction that turn, and the trigger for Particle Shield is very simple - just OnDamageDealt to one of your units, so it sounds like the game was not picking up that you actually had Particle Shield in your hand.

**Comment by onecrayon** [comment]
That’s very bizarre; the first time before I manual moded anything, the bluff timer did trigger, but that shouldn’t have effected the reaction count because I never played the Particle Shield. I double checked the log before I started trying alternate setups or reported the bug, and I had taken no reactions this turn. I’ll keep an eye out to see if it happens again; I play with Particle Shield pretty regularly.
