### ISSUE TITLE
Mark of the goddess and PBs 

### ISSUE THREAD

**Issue by danj3000** [Ashteki/ashteki#950]
I played Mark of the Goddess last night and targeted my opponents unexhausted Hammer Knight.  My opponent also had an Emberoot Lizard unexhausted, but it had a status token on it. I was able to deal the damage to his PB (Aradel) instead of being forced to kill the lizard

**Comment by 5H4Z** [comment]
I confirmed that the test card.controller.unitsInPlay.filter((c) => !c.exhausted).length === 1 is not functioning at all
